### ISSUE TITLE
Add filtering

### ISSUE THREAD

**Issue by epcim** [orf/git-workspace#242]
Can we design in this issue what way the filtering configuration for git-workspace could be done?

Requirements as I do understand:
* some wants to define what repositories to "update/sync"
* filter for repositories that within the scope of record in workspace.yaml (ie: the tool fetch today even repos of people I do follow, however if the name: is "myGithubName" it is desired to fetch only github.com/myGithubName namespace). This would at least allow to filter per GH organizations. (possibly the same per gitlab, gitea, etc..)
* `.filter(|r| r.name .....)` we could do even some regex, but it might be better to filter on graph query already
* how to record rules on configuration

**Comment by epcim** [comment]
Additionally, I found that git-workspace on GH does track/fetch all repositories I have contributed too, which can be nice feature, but shall have "off" switch.

**Comment by teto** [comment]
I concur. Te default behavior would just fill my HDD, I wouldn't mind entering the list of repos I want to sync manually

**Comment by orf** [comment]
This is fixed in 81727c262aa6d065ee3b6ac61efb70fcfbd33655: you can now `--exclude` repositories based on a regular expression. For example:

```toml
[[provider]]
provider = "github"
name = "django"
path = "github"
env_var = "GITHUB_TOKEN"
skip_forks = false
exclude = [
    "djangobench$",
    "dsf-.*"
]
```

The string matched against contains the _full_ path, so you can exclude anything.
